baseURL = "https://drinkmoxi.netlify.app/"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Northendlab | Blog Template"
[menu]
footer = []
[[menu.main]]
URL = "blog"
name = "Blog"
weight = "1"
[[menu.main]]
URL = "about"
name = "About"
weight = "2"
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Moxi Lab"
contact_form_action = "#"
copyright = "&copy; 2020 Moxi Lab All Rights Reserved"
description = "This is meta description"
google_analitycs_id = ""
google_tag_manager = ""
home = "Home"
logo = "images/moxi-text.png"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
title = "Hi, I'm John Smith Doe. <br> I help people make the  worlds best software"
[params.cta]
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
enable = true
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://gethugothemes.com/shop/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-github"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
