baseURL = "https://drinkmoxi.netlify.app/"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "drinkmoxi"
[menu]
footer = []
[[menu.main]]
URL = "blog"
name = "Blog"
weight = "1"
[[menu.main]]
URL = "about"
name = "About"
weight = "2"
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "drinkmoxi"
contact_form_action = "#"
copyright = "&copy; 2020 Moxi Lab All Rights Reserved"
description = ""
google_analitycs_id = ""
google_tag_manager = ""
home = "Home"
logo = "images/moxi-text.png"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
sub = "Moxi has everything you need with nothing you donâ€™t. We focus on the truly important ingredients to provide lasting energy and focus. We are currently hard at work to get moxi into your hands."
title = "Clean. Simple. Energy."
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/drinkmoxi/"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/drinkmoxi"
